# Site settings
title: Learning to code
header-img: img/home-bg.png
email: nickg73@gmail.com
copyright_name: nickg73
description: > # this means to ignore newlines until "baseurl:"
  Learning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nickg73
learn_profile: nickg73
email_username: nickg73@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
